CGL_TOPICS = {
    "reasoning": [
        "Analogy",
        "Classification & Odd One Out",
        "Number Series",
        "Letter Series",
        "Coding-Decoding",
        "Mathematical Operations & Sign Interchange",
        "Syllogism",
        "Venn Diagrams",
        "Blood Relations",
        "Direction Sense",
        "Dictionary Order",
        "Ranking & Order",
        "Dice & Cubes",
        "Mirror & Water Images",
        "Paper Folding & Cutting",
        "Embedded Figures",
        "Figure Series",
        "Counting Figures",
        "Missing Number & Number Matrix",
        "Puzzle",
        "Clock & Calendar",
        "Seating Arrangement",
        "Word Building",
    ],
    "general-awareness": [
        "History",
        "Geography",
        "Indian Polity",
        "Economics",
        "Physics",
        "Chemistry",
        "Biology",
        "Environment",
        "Art & Culture",
        "Awards & Honours",
        "Books & Authors",
        "Important Days",
        "Sports",
        "Static GK",
        "Current Affairs",
    ],
    "quant": [
        "Number System",
        "Simplification",
        "LCM & HCF",
        "Ratio & Proportion",
        "Percentage",
        "Average",
        "Profit, Loss & Discount",
        "Simple Interest",
        "Compound Interest",
        "Time & Work",
        "Pipes & Cisterns",
        "Time, Speed & Distance",
        "Trains",
        "Boats & Streams",
        "Mixture & Alligation",
        "Algebra",
        "Geometry",
        "Mensuration",
        "Trigonometry",
        "Data Interpretation",
        "Elementary Statistics",
        "Coordinate Geometry",
        "Heights & Distances",
    ],
    "english": [
        "Vocabulary",
        "Synonyms & Antonyms",
        "One Word Substitution",
        "Idioms & Phrases",
        "Spelling",
        "Error Spotting",
        "Sentence Improvement",
        "Fill in the Blanks",
        "Cloze Test",
        "Active & Passive Voice",
        "Direct & Indirect Speech",
        "Para Jumbles",
        "Reading Comprehension",
    ],
}
