LESSONS = [
    {
        "subject": "reasoning",
        "topic": "coding-decoding",
        "title": "Coding-Decoding: Find the rule before calculating",
        "intro": "Coding questions become faster when you test a small set of common transformations instead of guessing randomly.",
        "concept": "Start with alphabet positions A=1 to Z=26. Compare the same position in the original and coded word. Test direct shifts, reverse alphabet, value sums, substitution and rearrangement. Confirm the rule on at least two letters before applying it to the whole word.",
        "shortcut": "Use the first and last letter as a quick filter. If both follow the same shift or mapping, test the middle letters. Reject a rule immediately when one checked letter fails.",
        "worked_example": "If CODE becomes DPEF, each letter moves +1: C→D, O→P, D→E, E→F.",
        "memory_rule": "Shift → reverse → sum/value → substitution → rearrangement.",
        "common_traps": "Do not assume every code uses one rule. Some questions use position swaps plus a letter shift.",
        "estimated_minutes": 10,
    },
    {
        "subject": "reasoning",
        "topic": "number-series",
        "title": "Number Series: Check differences first",
        "intro": "Most series can be solved by testing a short hierarchy of patterns.",
        "concept": "Check first differences, second differences, alternating terms, multiplication/division with an added constant, then squares/cubes. Avoid jumping to complicated patterns before simple ones fail.",
        "shortcut": "Write only the gaps between terms. If the gaps form a clear series, you are done.",
        "worked_example": "3, 8, 15, 24, 35 gives differences 5, 7, 9, 11. Next difference is 13, so the next term is 48.",
        "memory_rule": "Difference → second difference → alternate → ×/÷ then ± → square/cube.",
        "common_traps": "Do not mix two patterns unless the series clearly alternates.",
        "estimated_minutes": 9,
    },
    {
        "subject": "reasoning",
        "topic": "dictionary-order",
        "title": "Dictionary Order: Stop at the first different letter",
        "intro": "Dictionary questions are pure left-to-right comparison.",
        "concept": "Compare words letter by letter. Ignore the common prefix. The first position where letters differ decides the order. If one word ends while all previous letters match, the shorter word comes first.",
        "shortcut": "Underline the first different letter in each word instead of comparing the entire word repeatedly.",
        "worked_example": "Calamity, Calcium, Calendar: after 'Cal', the next letters are a, c, e, so Calamity comes first.",
        "memory_rule": "Common prefix does not matter; first difference decides.",
        "common_traps": "Do not compare word length before checking the first differing letter.",
        "estimated_minutes": 6,
    },
    {
        "subject": "reasoning",
        "topic": "syllogism",
        "title": "Syllogism: Accept only what must be true",
        "intro": "SSC syllogism rewards minimum assumptions.",
        "concept": "Translate statements into simple set relations. 'All A are B' means A is inside B. 'Some A are B' means overlap exists. 'No A is B' means no overlap. A conclusion follows only when every valid diagram makes it true.",
        "shortcut": "For 'some' conclusions, look for a guaranteed common member. For 'no' conclusions, look for an explicit separation or a chain that forces separation.",
        "worked_example": "Some cartons are papers and some cartons are utensils. Therefore some papers are utensils if the same stated cartons connect both sets; do not invent extra overlap beyond what statements force.",
        "memory_rule": "Never convert 'All A are B' into 'All B are A'.",
        "common_traps": "Possibility and definite conclusion are different question types.",
        "estimated_minutes": 12,
    },
    {
        "subject": "reasoning",
        "topic": "mathematical-operations-and-sign-interchange",
        "title": "Sign Interchange: Substitute first, then use BODMAS",
        "intro": "These questions are easy to lose marks on when the original symbols are evaluated before replacement.",
        "concept": "Replace only the specified signs or numbers. Rewrite the entire expression with the new symbols. Then evaluate using BODMAS.",
        "shortcut": "Rewrite the expression once. Never try to do the swap mentally while calculating.",
        "worked_example": "If + and ÷ are interchanged, rewrite every + as ÷ and every ÷ as + before starting arithmetic.",
        "memory_rule": "Swap → rewrite → BODMAS.",
        "common_traps": "Do not evaluate left-to-right when multiplication/division are present.",
        "estimated_minutes": 7,
    },
    {
        "subject": "reasoning",
        "topic": "blood-relations",
        "title": "Blood Relations: Draw generations, not sentences",
        "intro": "A tiny family tree is more reliable than holding relationships in memory.",
        "concept": "Place people by generation. Use horizontal lines for same generation and vertical links for parent-child. Mark gender only when stated.",
        "shortcut": "Start from the person asked in the question and trace backwards instead of drawing every person.",
        "worked_example": "Mother's brother = maternal uncle. Father's sister's son = cousin.",
        "memory_rule": "Generation first, gender second, relation last.",
        "common_traps": "Do not assume gender from a name unless the question states it.",
        "estimated_minutes": 8,
    },
    {
        "subject": "reasoning",
        "topic": "direction-sense",
        "title": "Direction Sense: Use coordinates",
        "intro": "Coordinates remove confusion from multiple turns.",
        "concept": "Treat East as +x, West as −x, North as +y and South as −y. Update the position after each movement. For turns, track current facing direction separately.",
        "shortcut": "For final distance, use horizontal and vertical net movement; for shortest distance use Pythagoras when needed.",
        "worked_example": "5 km east then 3 km north gives position (5,3). Shortest distance from start is √34 km.",
        "memory_rule": "E +x, W −x, N +y, S −y.",
        "common_traps": "A left turn depends on the direction currently faced, not the page orientation.",
        "estimated_minutes": 8,
    },
    {
        "subject": "quant",
        "topic": "percentage",
        "title": "Percentage: Always identify the base",
        "intro": "Most percentage mistakes happen because the wrong base value is used.",
        "concept": "Percentage = part/base × 100. For percentage increase or decrease, the original value is the base. Useful conversions include 50%=1/2, 25%=1/4, 20%=1/5, 12.5%=1/8 and 33.33%=1/3.",
        "shortcut": "Use x% of y = y% of x when it makes mental arithmetic easier.",
        "worked_example": "200 increases to 250. Increase=50; 50/200×100=25%.",
        "memory_rule": "Change ÷ original × 100.",
        "common_traps": "An increase of 20% followed by a decrease of 20% does not return to the original value.",
        "estimated_minutes": 12,
    },
    {
        "subject": "quant",
        "topic": "average",
        "title": "Average: Convert immediately to total",
        "intro": "Average questions become simpler when you move between average and sum.",
        "concept": "Average = sum/count, so sum = average×count. When one item changes, track only the change in total.",
        "shortcut": "Use deviation from a convenient central value instead of adding large numbers directly.",
        "worked_example": "Average of 5 numbers is 18, so total is 18×5=90.",
        "memory_rule": "Average × count = total.",
        "common_traps": "When a person joins or leaves a group, the count changes as well as the total.",
        "estimated_minutes": 8,
    },
    {
        "subject": "quant",
        "topic": "ratio-and-proportion",
        "title": "Ratio: Convert parts into one unit",
        "intro": "A ratio tells you relative parts, not actual values.",
        "concept": "If A:B = 3:5, write A=3k and B=5k. Use any known difference, sum or actual value to find k.",
        "shortcut": "When a difference is given, compare it with the difference in ratio parts first.",
        "worked_example": "If A:B=3:5 and B−A=20, then 2 parts=20, so one part=10 and A=30, B=50.",
        "memory_rule": "Ratio parts × common unit = actual values.",
        "common_traps": "Do not add ratios from unrelated bases without converting them to a common term.",
        "estimated_minutes": 9,
    },
    {
        "subject": "english",
        "topic": "error-spotting",
        "title": "Error Spotting: Find the grammar anchor first",
        "intro": "Check the sentence in a fixed order instead of reading only by instinct.",
        "concept": "Start with subject-verb agreement, then tense, pronoun, article, preposition and parallel structure. Identify the main subject before matching the verb.",
        "shortcut": "Temporarily remove phrases such as 'of the students' to expose the true subject.",
        "worked_example": "'The list of items are ready' is wrong because the subject is singular 'list'; use 'is'.",
        "memory_rule": "Subject → verb → tense → pronoun → article/preposition.",
        "common_traps": "Words between subject and verb can distract you from the actual agreement.",
        "estimated_minutes": 10,
    },
    {
        "subject": "english",
        "topic": "synonyms-and-antonyms",
        "title": "Vocabulary: Reduce the word to a simple meaning",
        "intro": "You do not need a dictionary-style definition to eliminate options.",
        "concept": "Replace the target word with a simple meaning, identify its tone, then compare options. Use roots and context when the exact meaning is unfamiliar.",
        "shortcut": "For antonyms, first remove synonyms and words with the same tone.",
        "worked_example": "Scarce means 'not enough'; the opposite is abundant.",
        "memory_rule": "Simple meaning → tone → options.",
        "common_traps": "A related word is not automatically a synonym.",
        "estimated_minutes": 7,
    },
    {
        "subject": "general-awareness",
        "topic": "indian-polity",
        "title": "Polity Recall: Learn facts in clusters",
        "intro": "Static GK is retained better when one fact is linked to nearby facts.",
        "concept": "For each constitutional fact, store the article/topic, institution involved and one related fact. Revise through active recall rather than rereading.",
        "shortcut": "Create mini-clusters: Citizenship → Articles 5–11; Fundamental Rights → Part III; Directive Principles → Part IV.",
        "worked_example": "Instead of memorising Article 39A alone, connect it with Directive Principles and equal justice/free legal aid.",
        "memory_rule": "Fact + category + one neighbour fact.",
        "common_traps": "Do not mix constitutional articles with current office-holders; one is static, the other changes.",
        "estimated_minutes": 9,
    },
]
